[package]
name = "dcsrvrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = {version="0.5.0-rc.2", features=["json"] }

walkdir = "*"
filetime = "*"
env_logger = "*"
linked-hash-map = "*"
log = "*"
path-clean = "*"
tempfile = "*"
envy = "*"
serde = { version = "*", features = ["derive"] }

[profile.release]
strip = true
